### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by LokeYourC3PH** [AuraDevelopmentTeam/PowerMoney#13]
I would like to suggest the following features to this mod.

1: A command that lets you reload the config file so that you don't have to reboot the server in order to see the changes that are made in how much money is earned, etc. For example "/powermoney reload" or so would be helpful.

2: Values beyond 0.00, as on my modpack, the earning rates are miniscule due to several people having massive power farms in order to generate a lot of cash, and as such people that are only barely starting cannot see any progress towards their earned money, because it only goes far enough to show two digits below zero, but the config for example allows you to set the earnings to as low as six digits below zero, so being able to see that you actually made some progress at all would be nice.

3: A config option that allows you to cap how many PowerMoney Receiver blocks a player can have in total, so that they cannot make an infinite amount of these and place them everywhere.

That would be all for now, thanks for checking my post out :D

**Comment by BrainStone** [comment]
1: That should be possible to add.
2: A feature like that is being worked on.
3: First of all I don't think you understand how the mod works. It doesn't matter if you feed your energy into 1 block or 2 blocks. If the total is the same, the payout is the same as well. So limiting the amount of blocks per player won't do much.  
Now if you insist on doing that, I can recommend you our plugin [AuraBlockLimit](https://ore.spongepowered.org/AuraDevelopmentTeam/AuraBlockLimit), which does exactly that.

Though in your case I'd recommend you increase the log base. Or if you're using the root based calculation, then switch to the log based calculation. That'll debuff the high earners and allows you to increase the multiplier. In other words, rich people earn less, and poor earn more.

**Comment by LokeYourC3PH** [comment]
Oh I see, I thought there was a power limit to blocks yet, but in that case nr.3 isn't necessary as you say. But there is another request: Support for EconomyLite. I am getting my payouts, however the PowerMoney Receiver block says "Total Earnings: 0.00 C/s", even though I know I am getting money (I artifically increased the earnings to check that).

And yes, I use log based earnings to begin with, they earn less of course.

**Comment by BrainStone** [comment]
Any economy plugin is supported.

**Comment by LokeYourC3PH** [comment]
Hmm that is odd still, because the PowerMoney Receiver block says "0.00 Total Earnings", yet I get money all the time as I constantly check my /balance and see it slowly increases.

**Comment by BrainStone** [comment]
When it says `0.00`, it ommits the last few digits. And since the payouts occur by default every 15 seconds that means there is enough time for that to accumulate into more than `0.00`.

**Comment by LokeYourC3PH** [comment]
I increased the payout time to every 5 minutes instead of 15 seconds, so it should in theory be able to show something, but as you guys will be adding below 0.00 soon anyways it is not important as of now :D

**Comment by BrainStone** [comment]
The value in the GUI is the per second value.

**Comment by Z8MB1E** [comment]
Any updates on that `/powermoney reload` command?

**Comment by BrainStone** [comment]
Moved that to #18.

**Comment by BrainStone** [comment]
Reload has been implemented in #18.
