### ISSUE TITLE
Crash without IC2

### ISSUE THREAD

**Issue by DevTimur** [AuraDevelopmentTeam/PowerMoney#14]
I crash when placed Power Reciever.

- Minecraft: 1.12.2
- PowerMoney: 1.7.0
- Forge: 2784
- Other related mods: EnderPay, Vending

https://pastebin.com/0SHMWAXD

I believe you didn't mention IC2 as Required?

**Comment by BrainStone** [comment]
That’s certainly a bug. I’ll try to fix that ASAP

**Comment by BrainStone** [comment]
Could you try this version? https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.7.1.218-DEV/PowerMoney-1.12.2-1.7.1.218-DEV.jar

**Comment by BrainStone** [comment]
Fixed by 1.7.1

**Comment by BrainStone** [comment]
(https://minecraft.curseforge.com/projects/powermoney/files/2700545)
