### ISSUE TITLE
[Suggestion] Item trade?

### ISSUE THREAD

**Issue by DevTimur** [AuraDevelopmentTeam/PowerMoney#15]
Can you make someting with item trading?
Something you can automate buying\selling?
With configurable sales. With diminishing returns, the more you sell the cheaper it goes.
Maybe separate mod. Using EnderPay

**Comment by BrainStone** [comment]
This mod has nothing to do with item trading, so this suggestion is well out of scope.  
And considering I currently have shitton of projects to work on, I doubt I'l l get to making that as a separate mod any time soon.

**Comment by DevTimur** [comment]
k
