### ISSUE TITLE
Compatibility Issue with Grand Economy 1.2.x

### ISSUE THREAD

**Issue by nephatrine** [AuraDevelopmentTeam/PowerMoney#17]
#### Issue Description:

I'm using Grand Economy for my server's currency. When connecting Power Receiver to a power source the server crashes. If I install Grand Economy clientside and try in a single-player world I get the same issue and the game crashes so it's not restricted to server installations.

#### What happens:

The game crashes.

#### What you expected to happen:

Gameplay should continue normally.

#### Steps to reproduce:

1. Connect Power Receiver to power source.

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge 14.23.5.2838
- PowerMoney 1.7.1.221
- Grand Economy 1.2.1

#### Your most recent log or stack trace file where the issue was present:

It looks like Grand Economy made a change to their API in July [here](https://github.com/The-Fireplace-Minecraft-Mods/Grand-Economy/commit/3c52467741ba650e74aee6530d50d998f08d41ac) and that's what is causing the issue.

https://pastebin.com/56jddcnL

**Comment by BrainStone** [comment]
I see. That should be an easy fix. Working on it.

Do you need a release on Curse soon? (aka do you want to use it in a modpack?)

**Comment by BrainStone** [comment]
I think 33acdcf965877b6118aa983196a1d9299efba85f should fix it.

Try using https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.7.2.227-DEV/PowerMoney-1.12.2-1.7.2.227-DEV.jar to see if it works now. (If the link doesn't work, wait 5 minutes and try again. If it still doesn't work, then tell me)

**Comment by nephatrine** [comment]
That was super quick. ~~I can confirm this works.~~

EDIT: Well it worked it singleplayer now, but I'm getting a ticking world exception during startup when attempting to add it to the server. Did not get that with the previous version which did at least allow server to start up.

https://pastebin.com/82wfbC5C

**Comment by BrainStone** [comment]
The fix was simple. Didn't have to do anything.  
And you didn't answer my question :P

Also this crash seems to be completely unrelated to my mod. If you can reproduce it with a fresh world (and maybe a smaller set of mods) I can look into it. But please make it a new issue.
