### ISSUE TITLE
Suggestion: Introduce rate reload method

### ISSUE THREAD

**Issue by Z8MB1E** [AuraDevelopmentTeam/PowerMoney#18]
I have a suggestion!

Would it be possible to introduce a reload method that could reload the rates (log/root) through a command instead of restarting the server? I can't say I know how feasible this would be, but I've seen similar things done before with other mods.

Thanks for the great work!

**Comment by BrainStone** [comment]
I think it's better to have a seperate issue for this.

**Comment by BrainStone** [comment]
So erm yeah. Kinda stopped working on this as it didn't seem like many people were using it.

A reload command currently does not exist but if you're in single player you can change the config through the ingame config GUI so you can play around with the proper values in single player (for now) until you are happy with it.

**Comment by BrainStone** [comment]
Implemented by 68a31cd58558521e2c8e44da7f939a6ddfee4136
Please test: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney/1.7.3.246-DEV/PowerMoney-1.7.3.246-DEV.jar

**Comment by Z8MB1E** [comment]
> So erm yeah. Kinda stopped working on this as it didn't seem like many people were using it.
> 
> A reload command currently does not exist but if you're in single player you can change the config through the ingame config GUI so you can play around with the proper values in single player (for now) until you are happy with it.

That's alright! But hey, someone uses it! _*\*points at self\**_

> Implemented by [68a31cd](https://github.com/AuraDevelopmentTeam/PowerMoney/commit/68a31cd58558521e2c8e44da7f939a6ddfee4136)
> Please test: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney/1.7.3.246-DEV/PowerMoney-1.7.3.246-DEV.jar

I'll test that and let you know how it goes. Thanks for the very quick update on this suggestion!

**Comment by Z8MB1E** [comment]
So I've found that whenever I use the command, a usage message appears saying "Usage: powermoney reload". That's even if I use the command exactly as such: `/powermoney reload`. It also does not seem to be reloading the config. Any ideas?

**Comment by BrainStone** [comment]
I’ll look into it. The documentation on the whole thing is incredibly poor. So it’s quite hard knowing how things are without being able to test them. Which sadly was the case yesterday. I’ll get that fixed in no time.

**Comment by BrainStone** [comment]
Try this: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.7.3.249-DEV/PowerMoney-1.12.2-1.7.3.249-DEV.jar

A few things might not be 100% right but this should do for now. I'll publish soon.

**Comment by BrainStone** [comment]
Use that. All stuff fixed: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.7.3.251-DEV/PowerMoney-1.12.2-1.7.3.251-DEV.jar

**Comment by Z8MB1E** [comment]
> Use that. All stuff fixed: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.7.3.251-DEV/PowerMoney-1.12.2-1.7.3.251-DEV.jar

You're quick! Nice work. There is one problem though: The command gives a successful readback, but when I change the formulas in the server config and reload them, there is no discernible difference in game. Thoughts?

**Comment by BrainStone** [comment]
I might have used the wrong method to reload. 

Currently don’t have a good test setup so I’m mostly coding blind. I’ll figure it out though.

**Comment by BrainStone** [comment]
Here's the build: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.7.3.253-DEV/PowerMoney-1.12.2-1.7.3.253-DEV.jar

If you don't find any issues, I'll release it.

**Comment by Z8MB1E** [comment]
> Here's the build: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.7.3.253-DEV/PowerMoney-1.12.2-1.7.3.253-DEV.jar
> 
> If you don't find any issues, I'll release it.

I'll try it now and let you know. Thanks for the quick updates!

**Comment by BrainStone** [comment]
So?

**Comment by Z8MB1E** [comment]
> So?

So it looks like any time I place a Power Receiver block and hook it up to a power network, the server crashes. This didn't happen prior to the update. All the other mods running are the same.

Here is the [full server error log](https://pastebin.com/t41tGmXu). This is the [crash log](https://pastebin.com/SF0ytGe4).

**Comment by BrainStone** [comment]
That looks like a different issue. Please open a new issue for it.

**Comment by BrainStone** [comment]
There. Made one for you: https://github.com/AuraDevelopmentTeam/PowerMoney/issues/19

**Comment by Z8MB1E** [comment]
> There. Made one for you: #19

Awesome. Thank you very much. 👍
