### ISSUE TITLE
Crash when placing receiver

### ISSUE THREAD

**Issue by BrainStone** [AuraDevelopmentTeam/PowerMoney#19]
#### Issue Description:

When placing a receiver the server crashes.  
Reported by @Z8MB1E

#### What happens:

When placing a receiver the server crashes.

#### What you expected to happen:

No crashing

#### Steps to reproduce:

*sporadic*

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- PowerMoney: 1.7.3

#### Your most recent log or stack trace file where the issue was present:

- [Full Server Log](https://pastebin.com/t41tGmXu)
- [Crash Report](https://pastebin.com/SF0ytGe4)

**Comment by BrainStone** [comment]
@Z8MB1E try this build: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.7.4.257-DEV/PowerMoney-1.12.2-1.7.4.257-DEV.jar

**Comment by Z8MB1E** [comment]
> @Z8MB1E try this build: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.7.4.257-DEV/PowerMoney-1.12.2-1.7.4.257-DEV.jar

I'll give it a shot as soon as I can and let you know!

**Comment by Z8MB1E** [comment]
It's working! Thank you very much! 👍

**Comment by BrainStone** [comment]
Ok. The fix has been released to CurseForge and Ore.
