### ISSUE TITLE
Crush server

### ISSUE THREAD

**Issue by Whitebrim** [AuraDevelopmentTeam/PowerMoney#5]
#### What happens:
Tried to open nyan by pressing ASDF then server crushed.

#### Steps to reproduce:

1. press ASDF in block GUI

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- PowerMoney: 1.4.1.91
- Sponge: 1.12.2-2768-7.1.5-RC3513
- Forge: 1.12.2-14.23.5.2796
- Other related mods: http://brim.cf/mods.png

#### Your most recent log or stack trace file where the issue was present:

[pastebin/gist/etc link here]
http://brim.cf/logs.zip
```
[Or stack trace here (Remove this if you don't put anything here!)]
```

**Comment by BrainStone** [comment]
You can download the fixed version here: https://minecraft.curseforge.com/projects/powermoney/files/2665699

**Comment by Whitebrim** [comment]
thanx

**Comment by Whitebrim** [comment]
The same
code.re/eIn
