### ISSUE TITLE
Crush server #5.2

### ISSUE THREAD

**Issue by Whitebrim** [AuraDevelopmentTeam/PowerMoney#6]
#### What happens:
The same

#### What you expected to happen:
The same

#### Steps to reproduce:

1. The same
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- PowerMoney:
- Sponge:
- Forge: 
- Other related mods:

#### Your most recent log or stack trace file where the issue was present:

[pastebin/gist/etc link here]

https://code.re/eIn

```
[Or stack trace here (Remove this if you don't put anything here!)]
```

**Comment by BrainStone** [comment]
I see the error I made with the previous fix.
I'll shortly give you a new patch, so you can test it before I release it.

**Comment by Whitebrim** [comment]
ok

**Comment by Whitebrim** [comment]
Can you build .jar please?

**Comment by BrainStone** [comment]
It's building. 5 Minutes max

**Comment by BrainStone** [comment]
Here you go @Whitebrim: https://maven.project-creative.de/repository/auradev-snapshots/dev/aura/powermoney/PowerMoney-1.12.2/1.4.3.94-DEV/PowerMoney-1.12.2-1.4.3.94-DEV.jar

**Comment by Whitebrim** [comment]
works fine
![image](https://user-images.githubusercontent.com/23287829/51806333-ef2bcd80-2289-11e9-96be-38ba963655dd.png)

**Comment by Whitebrim** [comment]
can you tell me how it works and can I set price for energy or set limit to input (it eats all energy)

**Comment by BrainStone** [comment]
I'd prefer talking about that on my Discord: https://discord.me/bungeechat
